[Service]
ExecStart=
User=movie-comfyui
Group=movie-comfyui
WorkingDirectory=/srv/comfyui
ExecStart=/srv/comfyui/venv/bin/python main.py --listen 192.168.88.20 --port 8188 --disable-auto-launch --disable-pinned-memory --disable-dynamic-vram --reserve-vram 8 --disable-smart-memory
