<?php

return [
    'display_timezone' => env('MOVIE_DISPLAY_TIMEZONE', 'America/Los_Angeles'),
    'booking_horizon_days' => (int) env('MOVIE_BOOKING_HORIZON_DAYS', 14),
    'max_future_reservations' => (int) env('MOVIE_MAX_FUTURE_RESERVATIONS', 2),
    'start_step_minutes' => (int) env('MOVIE_START_STEP_MINUTES', 15),
    'cancellation_cutoff_minutes' => (int) env('MOVIE_CANCELLATION_CUTOFF_MINUTES', 30),
    'no_show_minutes' => (int) env('MOVIE_NO_SHOW_MINUTES', 15),
    'max_reservation_hours' => 8,
    'require_totp' => env('MOVIE_REQUIRE_TOTP', true),
    'global_free_space_floor_gb' => (int) env('MOVIE_FREE_SPACE_FLOOR_GB', 500),
    'workspace_enabled' => env('MOVIE_WORKSPACE_ENABLED', false),
    'company_codex_enabled' => env('MOVIE_COMPANY_CODEX_ENABLED', false),
    'workspace_image_max_kb' => 20 * 1024,
    'workspace_video_max_kb' => 32 * 1024,
    'video_root' => env('MOVIE_VIDEO_ROOT', '/srv/movie-outputs'),
    'style_demo_root' => env('MOVIE_STYLE_DEMO_ROOT', storage_path('app/style-demos')),
    'styles' => [
        [
            'skill' => 'h3-editorial-fashion-motion',
            'title_key' => 'ui.style_catalog.h3_editorial_fashion_motion.title',
            'description_key' => 'ui.style_catalog.h3_editorial_fashion_motion.description',
            'demo' => 'h3-editorial-fashion-motion.mp4',
        ],
        [
            'skill' => 'h3-surreal-miniature-absurdism',
            'title_key' => 'ui.style_catalog.h3_surreal_miniature_absurdism.title',
            'description_key' => 'ui.style_catalog.h3_surreal_miniature_absurdism.description',
            'demo' => 'h3-surreal-miniature-absurdism.mp4',
        ],
        [
            'skill' => 'h3-chibi-live-action-sticker',
            'title_key' => 'ui.style_catalog.h3_chibi_live_action_sticker.title',
            'description_key' => 'ui.style_catalog.h3_chibi_live_action_sticker.description',
            'demo' => 'h3-chibi-live-action-sticker.mp4',
        ],
        [
            'skill' => 'h3-creature-motion-replacement',
            'title_key' => 'ui.style_catalog.h3_creature_motion_replacement.title',
            'description_key' => 'ui.style_catalog.h3_creature_motion_replacement.description',
            'demo' => 'h3-creature-motion-replacement.mp4',
        ],
        [
            'skill' => 'h3-multiverse-portal-ensemble',
            'title_key' => 'ui.style_catalog.h3_multiverse_portal_ensemble.title',
            'description_key' => 'ui.style_catalog.h3_multiverse_portal_ensemble.description',
            'demo' => 'h3-multiverse-portal-ensemble.mp4',
        ],
        [
            'skill' => 'h3-deadpan-mockumentary-interview',
            'title_key' => 'ui.style_catalog.h3_deadpan_mockumentary_interview.title',
            'description_key' => 'ui.style_catalog.h3_deadpan_mockumentary_interview.description',
            'demo' => 'h3-deadpan-mockumentary-interview.mp4',
        ],
        [
            'skill' => 'h3-soft-body-physics-comedy',
            'title_key' => 'ui.style_catalog.h3_soft_body_physics_comedy.title',
            'description_key' => 'ui.style_catalog.h3_soft_body_physics_comedy.description',
            'demo' => 'h3-soft-body-physics-comedy.mp4',
        ],
        [
            'skill' => 'h3-retro-pixel-sprite-loop',
            'title_key' => 'ui.style_catalog.h3_retro_pixel_sprite_loop.title',
            'description_key' => 'ui.style_catalog.h3_retro_pixel_sprite_loop.description',
            'demo' => 'h3-retro-pixel-sprite-loop.mp4',
        ],
        [
            'skill' => 'h3-japanese-craft-commercial',
            'title_key' => 'ui.style_catalog.h3_japanese_craft_commercial.title',
            'description_key' => 'ui.style_catalog.h3_japanese_craft_commercial.description',
            'demo' => 'h3-japanese-craft-commercial.mp4',
        ],
        [
            'skill' => 'h3-micro-fpv-impossible-one-take',
            'title_key' => 'ui.style_catalog.h3_micro_fpv_impossible_one_take.title',
            'description_key' => 'ui.style_catalog.h3_micro_fpv_impossible_one_take.description',
            'demo' => 'h3-micro-fpv-impossible-one-take.mp4',
        ],
        [
            'skill' => 'h3-occlusion-orbit-ensemble',
            'title_key' => 'ui.style_catalog.h3_occlusion_orbit_ensemble.title',
            'description_key' => 'ui.style_catalog.h3_occlusion_orbit_ensemble.description',
            'demo' => 'h3-occlusion-orbit-ensemble.mp4',
        ],
        [
            'skill' => 'h3-character-intro-motion-card',
            'title_key' => 'ui.style_catalog.h3_character_intro_motion_card.title',
            'description_key' => 'ui.style_catalog.h3_character_intro_motion_card.description',
            'demo' => 'h3-character-intro-motion-card.mp4',
        ],
        [
            'skill' => 'h3-ancient-title-sequence',
            'title_key' => 'ui.style_catalog.h3_ancient_title_sequence.title',
            'description_key' => 'ui.style_catalog.h3_ancient_title_sequence.description',
            'demo' => 'h3-ancient-title-sequence.mp4',
        ],
        [
            'skill' => 'h3-interactive-creature-encyclopedia',
            'title_key' => 'ui.style_catalog.h3_interactive_creature_encyclopedia.title',
            'description_key' => 'ui.style_catalog.h3_interactive_creature_encyclopedia.description',
            'demo' => 'h3-interactive-creature-encyclopedia.mp4',
        ],
        [
            'skill' => 'h3-anime-character-showcase-pv',
            'title_key' => 'ui.style_catalog.h3_anime_character_showcase_pv.title',
            'description_key' => 'ui.style_catalog.h3_anime_character_showcase_pv.description',
            'demo' => 'h3-anime-character-showcase-pv.mp4',
        ],
        [
            'skill' => 'h3-material-carving-asmr',
            'title_key' => 'ui.style_catalog.h3_material_carving_asmr.title',
            'description_key' => 'ui.style_catalog.h3_material_carving_asmr.description',
            'demo' => 'h3-material-carving-asmr.mp4',
        ],
        [
            'skill' => 'h3-pop-art-split-screen-motion',
            'title_key' => 'ui.style_catalog.h3_pop_art_split_screen_motion.title',
            'description_key' => 'ui.style_catalog.h3_pop_art_split_screen_motion.description',
            'demo' => 'h3-pop-art-split-screen-motion.mp4',
        ],
        [
            'skill' => 'h3-dark-sci-fi-motion-poster',
            'title_key' => 'ui.style_catalog.h3_dark_sci_fi_motion_poster.title',
            'description_key' => 'ui.style_catalog.h3_dark_sci_fi_motion_poster.description',
            'demo' => 'h3-dark-sci-fi-motion-poster.mp4',
        ],
        [
            'skill' => 'h3-asymmetric-speed-duo-choreography',
            'title_key' => 'ui.style_catalog.h3_asymmetric_speed_duo_choreography.title',
            'description_key' => 'ui.style_catalog.h3_asymmetric_speed_duo_choreography.description',
            'demo' => 'h3-asymmetric-speed-duo-choreography.mp4',
        ],
        [
            'skill' => 'h3-layered-windsurfing-fashion-mv',
            'title_key' => 'ui.style_catalog.h3_layered_windsurfing_fashion_mv.title',
            'description_key' => 'ui.style_catalog.h3_layered_windsurfing_fashion_mv.description',
            'demo' => 'h3-layered-windsurfing-fashion-mv.mp4',
        ],
        [
            'skill' => 'h3-water-obstacle-variety-show',
            'title_key' => 'ui.style_catalog.h3_water_obstacle_variety_show.title',
            'description_key' => 'ui.style_catalog.h3_water_obstacle_variety_show.description',
            'demo' => 'h3-water-obstacle-variety-show.mp4',
        ],
        [
            'skill' => 'h3-two-part-character-reveal',
            'title_key' => 'ui.style_catalog.h3_two_part_character_reveal.title',
            'description_key' => 'ui.style_catalog.h3_two_part_character_reveal.description',
            'demo' => 'h3-two-part-character-reveal.mp4',
        ],
        [
            'skill' => 'h3-first-person-finger-controlled-dance',
            'title_key' => 'ui.style_catalog.h3_first_person_finger_controlled_dance.title',
            'description_key' => 'ui.style_catalog.h3_first_person_finger_controlled_dance.description',
            'demo' => 'h3-first-person-finger-controlled-dance.mp4',
        ],
    ],
    'manager_url' => env('MOVIE_MANAGER_URL', 'http://movie-workspace-manager:8080'),
    'manager_secret_file' => env('MOVIE_MANAGER_SECRET_FILE', '/run/secrets/manager_hmac_secret'),
    'terminal_router_secret_file' => env('MOVIE_TERMINAL_ROUTER_SECRET_FILE', '/run/secrets/router_hmac_secret'),
    'workspace_idle_minutes' => (int) env('MOVIE_WORKSPACE_IDLE_MINUTES', 240),
    'workspace_health_wait_seconds' => (int) env('MOVIE_WORKSPACE_HEALTH_WAIT_SECONDS', 45),
    'workspace_health_poll_milliseconds' => (int) env('MOVIE_WORKSPACE_HEALTH_POLL_MILLISECONDS', 500),
    'workspace_mutation_lock_seconds' => (int) env('MOVIE_WORKSPACE_MUTATION_LOCK_SECONDS', 180),
    'workspace_mutation_lock_wait_seconds' => (int) env('MOVIE_WORKSPACE_MUTATION_LOCK_WAIT_SECONDS', 120),
    'max_concurrent_workspaces' => (int) env('MOVIE_MAX_CONCURRENT_WORKSPACES', 3),
    'broker_control_url' => env('MOVIE_BROKER_CONTROL_URL', 'http://movie-ai-router:8080'),
    'local_node_broker_url' => env('MOVIE_LOCAL_NODE_BROKER_URL', 'http://movie-ai-broker:8080'),
    'broker_secret_file' => env('MOVIE_BROKER_SECRET_FILE', '/run/secrets/broker_hmac_secret'),
    'allowed_node_cidrs' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('MOVIE_ALLOWED_NODE_CIDRS', '192.168.88.0/24')),
    ))),
    'local_compute_node_slug' => env('MOVIE_LOCAL_COMPUTE_NODE_SLUG', 'ai-server-01'),
    'node_worker_port' => (int) env('MOVIE_NODE_WORKER_PORT', 8080),
    'node_heartbeat_stale_seconds' => (int) env('MOVIE_NODE_HEARTBEAT_STALE_SECONDS', 30),
    'required_worker_revision' => env('MOVIE_REQUIRED_WORKER_REVISION', ''),
    'required_workflow_revision' => env('MOVIE_REQUIRED_WORKFLOW_REVISION', ''),
    'codex_version' => env('MOVIE_CODEX_VERSION', '0.149.1'),
];
