Match User movie-model-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    AllowTcpForwarding remote
    AllowStreamLocalForwarding yes
    StreamLocalBindMask 0117
    StreamLocalBindUnlink yes
    GatewayPorts no
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
